name: Link check

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1 * *"

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Check links
        run: python scripts/check_links.py --online --include-resources
